name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    # TODO 1 : Using bazel , implement python test too later 
    # TODO 2 : Either sonar qube/codex to this test pipeline
    steps:
      # Step 1
      - uses: actions/checkout@v4
      # Step 2 : Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      # Step 3 : Run each unit test
      - name: Restore
        run: dotnet restore Backend/GraphDatabase.sln

      - name: Build
        run: dotnet build Backend/GraphDatabase.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Backend/Dotnet.Test/Dotnet.Test.csproj --configuration Release --logger "trx;LogFileName=results.trx" --results-directory test-results --no-build
      # Step 4 : Upload artifact(test-results) to test-results 
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
        if: ${{ always() }}